# Generated by Django 3.2.15 on 2022-10-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_id', models.CharField(max_length=20)),
                ('naccs_code', models.CharField(max_length=20)),
                ('latest_update_user', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoyagePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_of_origin', models.CharField(max_length=20)),
                ('port_of_destination', models.CharField(max_length=20)),
                ('estimate_time_in_hour', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('transit_time_in_hour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='VesselAPIs.voyageport')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='VesselAPIs.vessel')),
            ],
        ),
    ]
